"""empty message

Revision ID: 3ce9b5538a2f
Revises: None
Create Date: 2014-12-31 20:58:58.898691

"""

# revision identifiers, used by Alembic.
revision = '3ce9b5538a2f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linkfiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('videoId', sa.String(), nullable=True),
    sa.Column('audioFile', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('linkfiles')
    ### end Alembic commands ###
